### ISSUE TITLE
Fallan las validaciones cuando se intenta crear un cliente con datos de contacto

### ISSUE THREAD

**Issue by lndl** [brunocascio/UNLP-ruby-evaderApp#1]
Al intentar crear un cliente con contacto/s se informa que hay campos con errores pero no destaca a ninguno en particular. La prueba por consola arroja lo siguiente:

```
#<ActiveModel::Errors:0x007faa83adfb08 @base=#<Client id: nil, firstname: "Sarasa", lastname: "Pepepe", cuilt: "20-11111111-5", birthdate: "1998-01-01", genre: 0, i
dentification_number: "11111111", created_at: nil, updated_at: nil>, @messages={:"clients_contacts.client"=>["no puede estar en blanco"]}>
```

Revisar las validaciones.

**Comment by brunocascio** [comment]
Fixed 997d73bde7f37648d20c64e95976b30576e2f73b

**Comment by brunocascio** [comment]
Hola @lndl ! 

Estaba viendo el grade de moodle:

---

Hola Bruno:

El trabajo està realmente muy bien, casi excelente: muy prolijo, muy bien implementado y usa gemas consolidadas como nested_form y simple_form; pero desgraciadamente no està para aprobar en esta instancia **porque no permite crear un cliente con contactos.**
Por favor, corregì eso y listo. Te dejo el link del issue:...

Saludos.

---

Me quedó un poco confuso cual era el error. Lo que corregí fue el tema del mensaje que no lo mostraba. Pero los clientes con datos de contacto completos, deja crearlos.

Saludos y Gracias!

**Comment by lndl** [comment]
Hola Bruno, te dejo un requerimiento del POST que intento hacer (en el tag "entrega"):

```
Started POST "/clients" for 127.0.0.1 at 2016-01-15 09:06:25 -0300
Processing by ClientsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"/ayIDvF2Qa/o0KEW2dIPD/su3f/2ZUXAzuBEU3ZGHvWbC5P6DriZKorrvF7cdbn/PxmLrfNTChWPJVfJg6OR9w==", "client"=>{"firstname"=>"Pepe", "lastname"=>"Perez", "birthdate"=>"1986-02-21", "genre"=>"male", "identification_number"=>"99999999", "cuilt"=>"20-99999999-8", "clients_contacts_attributes"=>{"1452859570768"=>{"contact_id"=>"1", "value"=>"3333333333", "_destroy"=>"false"}, "1452859576472"=>{"contact_id"=>"2", "value"=>"hola@hola.com", "_destroy"=>"false"}}}, "commit"=>"Guardar"}
   (0.1ms)  begin transaction
  Contact Load (0.1ms)  SELECT  "contacts".* FROM "contacts" WHERE "contacts"."id" = ? LIMIT 1  [["id", 1]]
  Contact Load (0.1ms)  SELECT  "contacts".* FROM "contacts" WHERE "contacts"."id" = ? LIMIT 1  [["id", 2]]
  Client Exists (0.1ms)  SELECT  1 AS one FROM "clients" WHERE "clients"."cuilt" = '20-99999999-8' LIMIT 1
   (0.1ms)  rollback transaction
  Contact Load (0.6ms)  SELECT "contacts".* FROM "contacts"
  CACHE (0.0ms)  SELECT "contacts".* FROM "contacts"
  CACHE (0.0ms)  SELECT "contacts".* FROM "contacts"
  Rendered clients/_form.html.erb (33.9ms)
  Rendered clients/new.html.erb within layouts/application (34.4ms)
Completed 200 OK in 179ms (Views: 168.7ms | ActiveRecord: 1.1ms)
```

Si te guías por los parámetros, vas a ver que intento crear a un cliente (con todos sus datos básicos) + dos datos de contacto (un teléfono y un email). Este POST me tira error, pese a que está todo el form completo; de hecho, la vista señala que hay campos con errores pero no marca ninguno en particular.

En los cambios que introdujiste tampoco se corrige el error.

Ojalá se entienda. En última instancia mostrame un contraejemplo y comparamos criterios.

Saludos!

**Comment by brunocascio** [comment]
Gracias @lndl, si testeaba sólo con actualizar usuarios, no me iba a dar cuenta. El problema era que se estaba intentado crear la relacion "join" entre cliente y contacto, sin haber guardado el cliente primero (por ende no habia id de cliente). 

Le agregué `inverse_of` al modelo, y al parecer ahora funciona. 

Saluuuuuuu!

**Comment by lndl** [comment]
Perfecto, funcionamiento comprobado. Cierro el ticket.

**Comment by brunocascio** [comment]
Buenísimo @lndl!

Saludos!
